### ISSUE TITLE
manufacturers endpoint requires filterName query parameter

### ISSUE THREAD

**Issue by pyrschool** [ozcankursun/e-shop-back-end#3]
The endpoint that fetches mannufacturers (now it is the / but this should change, see #2), we are required to give `filterName` query parameter. If we don't have a filter, we should give `filterName=`.

The expoected behaviour is to get all manufacturers when we don't have a filterName parameter (eg when accessing127.0.0.1:300/)

Beware that we refer to / but we really mean the /manufacturers, see #2

**Comment by ozcankursun** [comment]
Can you check it please because when I request (http://localhost:3000/manufacturers?filterName=), I can take all data.
Should I add the filter for clothes and orders?
